#!/usr/bin/env python

import tic

player_1 = tic.RandomPlayer()
player_2 = tic.RandomPlayer()

game = tic.Game(player_1, player_2)

while game.next():
    game.show()


if game.winner == player_1:
    print('Player 1 won!')
elif game.winner == player_2:
    print('Player 2 won!')
else:
    print('Draw!')
